### ISSUE TITLE
I can't install the app, the commands don't run in Win PowerShell (Missing Git)

### ISSUE THREAD

**Issue by SemenTankist2007** [Strip3s/PhoenixBot#113]
I don't know anything about code so please help me to install the bot... Thank you very much.

**Comment by jack60612** [comment]
did you install python and git?

**Comment by SemenTankist2007** [comment]
Yes, I did install Python, but what is git? I don't know a whole lot about coding...

**Comment by SemenTankist2007** [comment]
Oh, I Googled it, it's a control system... So, ok, I'll install it, but then what?

**Comment by jack60612** [comment]
then follow the instructions

> Oh, I Googled it, it's a control system... So, ok, I'll install it, but then what?

**Comment by jack60612** [comment]
they will work fine now lol you just didn't have the required things installed

**Comment by SemenTankist2007** [comment]
Hmmmmm, ok, thanks, I'll do it then.

**Comment by SemenTankist2007** [comment]
I'll close this discussion when I successfully install it.

**Comment by jack60612** [comment]
i added the extra steps to the readme to help other new users

**Comment by SemenTankist2007** [comment]
Alright, thanks!

**Comment by jack60612** [comment]
> Alright, thanks!
it works right @SemenTankist2007?

**Comment by SemenTankist2007** [comment]
Oh, I can't check it right now, I'm on a Chromebook. I will when I get home to my PC.

**Comment by SemenTankist2007** [comment]
Ok, I checked, and it works, but I can't add a task for some reason... When I fill everything out and press "add task" nothing happens. [Apple iMac (Late 2013) 21.5 in macOS X]

**Comment by SemenTankist2007** [comment]
I installed git through terminal by installing homebrew though terminal :D
