### ISSUE TITLE
IndexError for e_key

### ISSUE THREAD

**Issue by Strip3s** [Strip3s/PhoenixBot#13]
**Describe the bug**
Currently, there's a vault.json file within the DATA/ folder within the current repo. This file is used for generating the CC encryption secret key for proper security protocol. You will normally receive the following stacktrace if cloned a new. 

`(env) PS C:\Users\T'Challa\Desktop\PhoenixBot> python app.py
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from pages.homepage import HomePage,TaskTab
  File "C:\Users\T'Challa\Desktop\PhoenixBot\pages\homepage.py", line 2, in <module>
    from sites.walmart import Walmart
  File "C:\Users\T'Challa\Desktop\PhoenixBot\sites\walmart.py", line 2, in <module>
    from utils import send_webhook
  File "C:\Users\T'Challa\Desktop\PhoenixBot\utils.py", line 30, in <module>
    e_key = keys[0]['generated_key_secret'].encode()
IndexError: list index out of range`

The vault.json file is no longer necessary within the actual repo since the code will autogenerate the file if it exists.

**Workaround**

Delete the vault.json AND profiles.json file within your data folder. FYI This will delete existing profiles if done!

**Comment by R1fast** [comment]
Thank you for posting the work-around!
