### ISSUE TITLE
Not importing the PyQt?

### ISSUE THREAD

**Issue by atanc** [Strip3s/PhoenixBot#33]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> git clone https://github.com/Strip3s/PhoenixBot/
Cloning into 'PhoenixBot'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 190 (delta 2), reused 3 (delta 0), pack-reused 182R
Receiving objects: 100% (190/190), 1.12 MiB | 12.99 MiB/s, done.
Resolving deltas: 100% (97/97), done.
PS C:\WINDOWS\system32> cd PhoenixBot
PS C:\WINDOWS\system32\PhoenixBot> python -m venv ./env
PS C:\WINDOWS\system32\PhoenixBot> ./env/Scripts/activate
./env/Scripts/activate : File C:\WINDOWS\system32\PhoenixBot\env\Scripts\Activate.ps1 cannot be loaded because running
scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ ./env/Scripts/activate
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\WINDOWS\system32\PhoenixBot> pip install -r requirements.txt
Requirement already satisfied: pyqt5==5.14.2 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from -r requirements.txt (line 1)) (5.14.2)
Requirement already satisfied: js2py==0.68 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from -r requirements.txt (line 2)) (0.68)
Requirement already satisfied: requests==2.23.0 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from -r requirements.txt (line 3)) (2.23.0)
Requirement already satisfied: lxml==4.5.0 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from -r requirements.txt (line 4)) (4.5.0)
Requirement already satisfied: darkdetect==0.1.1 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from -r requirements.txt (line 5)) (0.1.1)
Requirement already satisfied: colorama==0.4.3 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from -r requirements.txt (line 6)) (0.4.3)
Requirement already satisfied: selenium==3.141.0 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from -r requirements.txt (line 7)) (3.141.0)
Requirement already satisfied: chromedriver-py==86.0.4240.22 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from -r requirements.txt (line 8)) (86.0.4240.22)
Requirement already satisfied: pycryptodome in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from -r requirements.txt (line 9)) (3.9.9)
Requirement already satisfied: webdriver_manager==3.2.2 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from -r requirements.txt (line 10)) (3.2.2)
Requirement already satisfied: PyQt5-sip<13,>=12.7 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from pyqt5==5.14.2->-r requirements.txt (line 1)) (12.8.1)
Requirement already satisfied: pyjsparser>=2.5.1 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from js2py==0.68->-r requirements.txt (line 2)) (2.7.1)
Requirement already satisfied: tzlocal>=1.2 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from js2py==0.68->-r requirements.txt (line 2)) (2.1)
Requirement already satisfied: six>=1.10 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from js2py==0.68->-r requirements.txt (line 2)) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests==2.23.0->-r requirements.txt (line 3)) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests==2.23.0->-r requirements.txt (line 3)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests==2.23.0->-r requirements.txt (line 3)) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from requests==2.23.0->-r requirements.txt (line 3)) (1.25.11)
Requirement already satisfied: configparser in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from webdriver_manager==3.2.2->-r requirements.txt (line 10)) (5.0.1)
Requirement already satisfied: crayons in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from webdriver_manager==3.2.2->-r requirements.txt (line 10)) (0.4.0)
Requirement already satisfied: pytz in c:\users\a\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from tzlocal>=1.2->js2py==0.68->-r requirements.txt (line 2)) (2020.4)
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'C:\Users\A\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.
PS C:\WINDOWS\system32\PhoenixBot> python app.py
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: The specified module could not be found.
PS C:\WINDOWS\system32\PhoenixBot>

Idk how to fix it

**Comment by Strip3s** [comment]
@atanc  This isn't a bug. If you went to the link from the error you posted, it will give you the answer.  

`File C:\WINDOWS\system32\PhoenixBot\env\Scripts\Activate.ps1 cannot be loaded because running
scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.`

Just enable the proper PowerShell policy

`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned`

**Comment by atanc** [comment]
> @atanc This isn't a bug. If you went to the link from the error you posted, it will give you the answer.
> 
> `File C:\WINDOWS\system32\PhoenixBot\env\Scripts\Activate.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.`
> 
> Just enable the proper PowerShell policy
> 
> `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned`

(env) PS C:\WINDOWS\system32\PhoenixBot> python app.py
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: The specified module could not be found.
(env) PS C:\WINDOWS\system32\PhoenixBot> Set-ExecutionPolicy RemoteSigned

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
(env) PS C:\WINDOWS\system32\PhoenixBot> python app.py
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: The specified module could not be found.
(env) PS C:\WINDOWS\system32\PhoenixBot>


still not working. idk how to import the Qt parts.
