### ISSUE TITLE
[BUG] GUI Window Size To Small

### ISSUE THREAD

**Issue by hood1989** [Strip3s/PhoenixBot#44]
After launching the .py program it opens the gui window however the window is so small i cant access any options.

How can i resize the screen? I assume I will need to adjust one of the config files...

**Comment by broglea** [comment]
@hood1989

Please provide a screenshot and also let us know what operating system you run and what you're screen resolution is set to.

**Comment by hood1989** [comment]
Err it was a stupid error on my behalf...

I just resized my resolution and it fixed the problem
