### ISSUE TITLE
Get LATEST driver version for 87.0.4280

### ISSUE THREAD

**Issue by ManukuSol** [Strip3s/PhoenixBot#48]
After updating to latest version of Chrome driver, Chrome opens Walmart homepage but does not bring me to a captcha. I click the Bot prompt which leads to a "Error Adding to Cart" message --> this continues in a cycle. So I am not getting a captcha, what could be wrong?

Is this a driver issue or a browser issue?

**Comment by Forecastlife** [comment]
Having the same issue and i am using the same driver. Console will load the page once but then gets caught up in a Captcha loop. The URL that opens when i try to solve the captcha is the Walmart home page.  I have tried to troubleshoot to the best of my ability (i'm a pleb R data scientist don't laugh).

Here is my console output:
`[2020-11-27` 17:02:43][TASK 1] CAPTCHA - Opening Product Page

[WDM] - Current google-chrome version is 87.0.4280
[WDM] - Get LATEST driver version for 87.0.4280
[WDM] - Driver [C:\Users\jonat\.wdm\drivers\chromedriver\win32\87.0.4280.20\chromedriver.exe] found in cache
[2020-11-27 17:03:05][TASK 1] Loading Product Page
[2020-11-27 17:03:05][TASK 1] Waiting For Restock
[2020-11-27 17:03:08][TASK 1] Loading Product Page
[2020-11-27 17:03:08][TASK 1] CAPTCHA - Opening Product Page

[WDM] - Current google-chrome version is 87.0.4280
[WDM] - Get LATEST driver version for 87.0.4280
[WDM] - Driver [C:\Users\jonat\.wdm\drivers\chromedriver\win32\87.0.4280.20\chromedriver.exe] found in cache
[2020-11-27 17:03:11][TASK 1] Stopped``

I tried these two things:

1. tried changing the call in the "open browser" function in Util like so:
`option.add_argument('--disable-blink-features=AutomationControlled')`

This was only an update to the call you guys had implemented (supposedly was supposed to be used on new drivers) and did not fix the problem. I think this may be the root of the issue as my chrome browser still has the banner that says it's being run by an automated process when I detor from phoenixbot to "solve" the captcha. 

2. Tried to edit the chrome driver JS code using a HEX editor using the following instructions:
  
[https://piprogramming.org/articles/How-to-make-Selenium-undetectable-and-stealth--7-Ways-to-hide-your-Bot-Automation-from-Detection-0000000017.html](url)

This doesn't seem to have helped either but I am happy to have ruled it out as a fix.
