### ISSUE TITLE
[BUG] EWW! I FOUND A BUG

### ISSUE THREAD

**Issue by hardt0303** [Strip3s/PhoenixBot#51]
# Expected Behavior

Complete the checkout at WalMart

# Actual Behaviour

Stops and does not complete the checkout process and when it pulls chrome up after adding to cart it is the home page of wal-mart

# Screenshots

Place any informational screenshots here. 

# Repro Steps

Please include the steps of how we can reproduce this issue on our end. 

I.E.

# Desktop Configuration
Does it on chrome both OS and Windows

# Additional Context

**Comment by hardt0303** [comment]
I am to much of a newb to even try and figure it out

**Comment by Strip3s** [comment]
> I am to much of a newb to even try and figure it out

We need a bit more information about the bug you're experiencing to really help out. When you get some more information about what's really happening, recreate the bug. You try asking the community on discord for some more troubleshooting help.
