### ISSUE TITLE
[BUG] Bestbuy Stuck on Loading Page

### ISSUE THREAD

**Issue by Forecastlife** [Strip3s/PhoenixBot#53]
# Expected Behavior

Started a new task on bestbuy. Using the new chrome driver (87.0.4280). Could be a part of it. 

# Actual Behaviour

Sits on the loading page status and does not actually load

1. Go to add task
2. Click on bestbuy
3. Start the task

# Desktop Configuration
 - OS: windows 10
 - Browser chrome (87.0.4280)

# Additional Context

**Comment by Strip3s** [comment]
Which branch was this performed on? @Forecastlife

**Comment by Forecastlife** [comment]
Master branch.. I did try to load the best buy fix but there seemed to be some typos in the code giving me errors.

**Comment by Strip3s** [comment]
> Master branch.. I did try to load the best buy fix but there seemed to be some typos in the code giving me errors.

This will be more than likely resolved within the incoming refactor update i'm about to push up this week.
