### ISSUE TITLE
Discord Link

### ISSUE THREAD

**Issue by bbrookshire** [Strip3s/PhoenixBot#55]
The Discord link is still invalid (even after the last update 3 days ago)

**Comment by Forecastlife** [comment]
Interested in this link too..

**Comment by Strip3s** [comment]
There will be an update with an incoming PR this week to update the original link to never expire. 

Use this one, for now, @bbrookshire @Forecastlife 
https://discord.gg/4HB9kzQC

This will expire in a day though.
