### ISSUE TITLE
[BUG] EWW! I FOUND A BUG

### ISSUE THREAD

**Issue by dudeistpriest** [Strip3s/PhoenixBot#56]
# Expected Behavior

Run task on Target, Best Buy, GameStop

# Actual Behaviour

Target - status stuck on "Changing Value in Chromedriver" 
PermissionError: [Errno 13] Permission denied: 'C:\\...\\PhoenixBot\\env\\lib\\site-packages\\chromedriver_py\\chromedriver_win32.exe'
Not sure if I need to update requirements from 86.0.4240 to the new version?

Best Buy - status stuck on "Loading Product Page" 
No updates in the terminal either

GameStop - status is "Stopped"
Opens up a new chrome window with data:, in the URL bar 
[WDM] - Current google-chrome version is 86.0.4240
[WDM] - Get LATEST driver version for 86.0.4240
[WDM] - Driver [C:\...\.wdm\drivers\chromedriver\win32\86.0.4240.22\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:59038/devtools/browser/343fc9a5-5e59-4867-bae4-d29fe535cd4e
[18784:12912:1128/155205.447:ERROR:browser_gpu_channel_host_factory.cc(167)] Failed to launch GPU process.

# Screenshots

Place any informational screenshots here. 

# Repro Steps

Clicking the run button on tasks to those sites 

I.E.

# Desktop Configuration
 - OS: Win 10 pro
 - Browser Chrome 86.0.4240.198 (Official Build) (64-bit)
 - Version 49 I think? not sure how to check in visual studios but I recloned today

# Additional Context

**Comment by hardt0303** [comment]
On the mac target app wont input username and password, but the program runs fine. On my windows I get the same problem

**Comment by jack60612** [comment]
Yep you need to use sudo due the fact that we updated the chrome driver version.

**Comment by jack60612** [comment]
@hardt0303

**Comment by jack60612** [comment]
you need to git pull / redownload the repo and if you are still having an issue  please submit a new bug report with more information including your log.
