### ISSUE TITLE
Discord Link is not persistent in Readme.

### ISSUE THREAD

**Issue by arcreigh** [Strip3s/PhoenixBot#61]
Hey all!
Just wanted to let you know that the discord link is not persistent and is expiring.

**Comment by Strip3s** [comment]
There will be an update with an incoming PR this week to update the original link to never expire.

Use this one, for now, @arcreigh 
https://discord.gg/4HB9kzQC

This will expire in a day though.

**Comment by arcreigh** [comment]
Sounds good! Looks like that invite was also invalid or expired.  I'll wait for the update for now. Thanks!
