### ISSUE TITLE
[BUG] walmart.py throws error: Error Loading Product Page (line 79 AttributeError module 'settings' has no attribute 'rand_delay_start')

### ISSUE THREAD

**Issue by GoTTi74** [Strip3s/PhoenixBot#70]
# The walmart.py code contains wrong attributes

Therefore an error is thrown:

> Error Loading Product Page (line 79 AttributeError module 'settings' has no attribute 'rand_delay_start')

Code in line 74:
`                                time.sleep(random_delay(self.monitor_delay, settings.rand_delay_start,`

Code in line 170
`                            random_delay(self.monitor_delay, settings.rand_delay_start, settings.rand_delay_stop))`

The attributes do not exist
```
settings.rand_delay_start
settings.rand_delay_stop
```

The correct attributes are:
```
settings.random_delay_start
settings.random_delay_stop
```

**Comment by Strip3s** [comment]
Good catch. I'll push a fix for it now
