### ISSUE TITLE
[BUG] GameStop fails at Loggin In

### ISSUE THREAD

**Issue by NiteshMistry** [Strip3s/PhoenixBot#76]
# Expected Behavior

Should log and wait for the product to be in stock.
Target and BestBuy tasks are working.

# Actual Behaviour

GameStop fails at Loggin In. Please see the below error and steps to generate it.

# Screenshots

Place any informational screenshots here. 

# Repro Steps

Product Link: https://www.gamestop.com/video-games/playstation-5/consoles/products/playstation-5/11108140.html?utm_source=rakutenls&utm_medium=affiliate&utm_content=NowInStock&utm_campaign=10&utm_kxconfid=tebx5rmj3&cid=afl_10000087&affID=77777&sourceID=AKGBlS8SPlM-9_iat2FI8MNlM3ehRrnDQw

1. Create a task
2. Click start in the action
3. GameStop opens in the new Chrome window
4. No login window appears
5. Log in fails with the below error

**Error:**
```
[2020-12-14 16:05:53][TASK 3] Starting GameStop
[2020-12-14 16:05:53][TASK 3] Logging In..
Traceback (most recent call last):
  File "C:\Users\ASUS\Downloads\PhoenixBot\pages\homepage.py", line 514, in run
    GameStop(self.task_id, self.status_signal, self.image_signal, self.product, profile, proxy, self.monitor_delay, self.error_delay, self.max_price)
  File "C:\Users\ASUS\Downloads\PhoenixBot\sites\gamestop.py", line 27, in __init__
    self.login()
  File "C:\Users\ASUS\Downloads\PhoenixBot\sites\gamestop.py", line 59, in login
    wait(self.browser, self.LONG_TIMEOUT).until(EC.element_to_be_clickable((By.LINK_TEXT, "MY ACCOUNT")))
  File "C:\Users\ASUS\Downloads\PhoenixBot\env\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

The login option is also missing in the GameStop window opened by Selenium. GameStop detecting automated test software?

**GameStop window opened by Selenium:**
![image](https://user-images.githubusercontent.com/9368802/102136808-e9ace180-3e27-11eb-8f79-1c97bab12c90.png)

**GameStop window opened manually:**
![image](https://user-images.githubusercontent.com/9368802/102137056-3d1f2f80-3e28-11eb-97dc-73e06c532a7e.png)

# Desktop Configuration
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (64-bit)

**Comment by dotex3** [comment]
The issue is the browser sizing. If the window isn't the right size then the login is moved to the hamburger menu and doesn't appear after resizing. Solution is to add `self.browser.maximize_window()` at the start of the login. Haven't tested it yet but I assume the window can be resized back down after login is complete.
