### ISSUE TITLE
Auto Checknow needs to be established rn

### ISSUE THREAD

**Issue by Trout27Elite** [Strip3s/PhoenixBot#78]
# Summary

BestBuy needs autocheck out. Needs resolved in the next 10hrs has a release at 8am central. I need to secure it. Let me know. Thanks

# MVP Features
AUTO CHECKOUT DONE WITHIN THE NEXT 8 HRS
What would be required at a minimum in order to get the feature implemented within the source?

# Additional Information
GET IT DONE.
Please let our team know any additional information you would like to provide.

**Comment by Strip3s** [comment]
Closing this. It's open source so feel free to contribute if you need it this badly.
