### ISSUE TITLE
[BUG] With saving accounts it won't save what state I live in 

### ISSUE THREAD

**Issue by CreightonJackson** [Strip3s/PhoenixBot#81]
# Expected Behavior

Should remember the state I live in

# Actual Behaviour

Keeps resetting my state to AL

# Screenshots

Place any informational screenshots here. 

# Repro Steps

I.E.

1. Go to 'Profile'
2. Click on 'United States'
3. Click on state
4. Scroll down to 'your state'
5. Exit
6. Open back up and you'll see that the state is listed as AL

# Desktop Configuration
 - OS: Windows 10
 - Browser Chrome 
 - Version idk

# Additional Context

**Comment by ima9rd** [comment]
Addressed in #82.
