### ISSUE TITLE
[BUG] Only Wallmart working.

### ISSUE THREAD

**Issue by Jackg093** [Strip3s/PhoenixBot#88]
Hello, I've really just been using your tool using the front end, the error I get when I try to run the task for anything other than Wallmart is; can't find this url etc.  

I am on mac using chrome: Version 88.0.4324.96 (Official Build) (x86_64)  

Please feel free to let me know if the error is in the code or my operation of the front end.  Perhaps my browser, which is fully updated.

**Comment by jack60612** [comment]
use chrome 89 and try it now after updating repo @Jackg093

**Comment by jack60612** [comment]
IF  you still have an issue reopen a bug request with more advanced logs
