### ISSUE TITLE
[BUG] Best Buy and WalMart are not working

### ISSUE THREAD

**Issue by MarylandEd** [Strip3s/PhoenixBot#94]
# Expected Behavior

BestBuy and WalMart should log in and pull the item into the queue, refresh, and purchase.

# Actual Behaviour

BestBuy won't load the item and WalMart requires Captcha every minute or so. The bot can't function if captcha is triggered constantly.

# Screenshots

Place any informational screenshots here. 

# Repro Steps

Please include the steps of how we can reproduce this issue on our end. 

I.E.

# Desktop Configuration
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 88.0.4324.190

# Additional Context

**Comment by jack60612** [comment]
@MarylandEd the issue should be fixed as we updated chrome to the newest version
